/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncolis;


//import projetgestioncolis.Cnx;
import java.sql.*;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 *
 * @author Electronic Store
 */
public class inscriptionClient extends javax.swing.JFrame {
        Connection cn;
        Statement st;
        ResultSet rs;
    /**
     * Creates new form inscriptionClient
     */
    public inscriptionClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        popupMenu1 = new java.awt.PopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        DesigntionLabel = new javax.swing.JLabel();
        identifiantLabel = new javax.swing.JLabel();
        AdresseLabel = new javax.swing.JLabel();
        GSMLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        Designation = new javax.swing.JTextField();
        Adresse = new javax.swing.JTextField();
        Gsm = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        identifiant = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        DesigntionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DesigntionLabel.setText("Designation");

        identifiantLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        identifiantLabel.setText("CIN/ICE");

        AdresseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdresseLabel.setText("Adresse");

        GSMLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        GSMLabel.setText("GSM");

        EmailLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EmailLabel.setText("Email");

        Designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesignationActionPerformed(evt);
            }
        });
        Designation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DesignationKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DesignationKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DesignationKeyTyped(evt);
                KeyPad(evt);
            }
        });

        Gsm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GsmKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Valider");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Inscription");
        jLabel1.setAlignmentX(2.0F);
        jLabel1.setAlignmentY(2.0F);
        jLabel1.setAutoscrolls(true);

        jLabel2.setMaximumSize(new java.awt.Dimension(1069, 1262));
        jLabel2.setMinimumSize(new java.awt.Dimension(1069, 1262));

        identifiant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                identifiantKeyPressed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(51, 51, 255));
        button1.setLabel("button1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu6.setText("Edit");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(identifiantLabel)
                                    .addComponent(DesigntionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(114, 114, 114)
                                        .addComponent(GSMLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                        .addComponent(Gsm, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(300, 300, 300)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(AdresseLabel)
                                                    .addComponent(Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Designation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DesigntionLabel)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AdresseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Designation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(identifiantLabel)
                            .addComponent(Gsm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(GSMLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(EmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesignationActionPerformed

    private void DesignationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DesignationKeyTyped
       
    }//GEN-LAST:event_DesignationKeyTyped

    private void KeyPad(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyPad
        // TODO add your handling code here:
    }//GEN-LAST:event_KeyPad

    private void DesignationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DesignationKeyPressed
    }//GEN-LAST:event_DesignationKeyPressed
    private void identifiantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identifiantKeyPressed
  
    }//GEN-LAST:event_identifiantKeyPressed

    private void DesignationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DesignationKeyReleased
    
    }//GEN-LAST:event_DesignationKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
           cn =Cnx.connect();
           st = cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
           rs = st.executeQuery("select C.* from Client C");
           id = st.executeQuery("select count( C.idClient) as clt from Client C");
//             int num= Integer.parseInt(id.getObject(1).toString());

        } catch (Exception ex) {ex.printStackTrace(); 
          System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//EmailField 
            String email =Email.getText();
            Pattern emailPattern =Pattern.compile("@", Pattern.CASE_INSENSITIVE);
            Matcher emailMatcher =emailPattern.matcher(email);
            boolean emailMatchfound =emailMatcher.find();
            
                if(emailMatchfound==false ){
//                  EmailZone.setText("en forme d'un email '@'");
                }
            
        
//DesignationField obliger des characteres et des espaces
            String des =Designation.getText();
            Pattern pattern =Pattern.compile(" ", Pattern.CASE_INSENSITIVE);
//            Pattern  Pattern1= pattern.compile("[a-zA-Z]+", Pattern.CASE_INSENSITIVE);
//            Matcher matcher1 =Pattern1.matcher(des);
            Matcher matcher =pattern.matcher(des);
//            boolean matchfound1 = matcher1.find();
            boolean matchfound =matcher.find();
            
                if(matchfound==false  ){
//                  Ds.setText("Entre votre Nom et Prenom");
                }
            
//creer un code d'utilisateur
            int n=10;
            String password ="";
            for (int i=0; i<n;i++){           
                Random rand = new Random();
                char c = (char)(rand.nextInt(26) + 97);
                password += c;
            }
           
           
//Pour ajouter un line dans la base de donnee
        try{
         
            rs.moveToInsertRow();
            rs.updateInt(1,3632);
            rs.updateString(2, Designation.getText());
            rs.updateString(3,identifiant.getText());
            rs.updateString(4, Email.getText());
            rs.updateInt(5,1);
            rs.updateDate(6, new Date(System.currentTimeMillis()) );
            rs.updateInt(7, Integer.valueOf(Gsm.getText()));
            rs.updateString(8, Adresse.getText());
            rs.updateString(9, password);
            rs.insertRow();


//                 Date dt =new Date(System.currentTimeMillis());
//               String  Des = Designation.getText();
//                String id=  identifiant.getText();
//                String adress = Adresse.getText();
//                int Tel=Integer.valueOf(Gsm.getText());
//                String em=  Email.getText();
//                
//                String req="insert into Client(idClient,Designation,Identifiant,Email,Statut,DateInscription,gsm,adress,passwordclient) values ('seq_person.CURRVA ,'"+Des+","+id+","+em+",1,"+dt+","+Tel+","+adress+","+password+"')";
//                  Cnx.executerMAJ(req);
            }catch(Exception ex) {ex.printStackTrace();
              System.out.println(ex.getMessage());
        JOptionPane.showMessageDialog(rootPane,"format incorrect");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GsmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GsmKeyPressed
//       try {
//       
//       int  x = Integer.parseInt(Gsm.getText());
//       EmailZone.setText("");
//    } catch (NumberFormatException nfe) {
//        EmailZone.setText("*only number");
//        Gsm.setText("");
//        
//    }
    }//GEN-LAST:event_GsmKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inscriptionClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adresse;
    private javax.swing.JLabel AdresseLabel;
    private javax.swing.JTextField Designation;
    private javax.swing.JLabel DesigntionLabel;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel GSMLabel;
    private javax.swing.JTextField Gsm;
    private java.awt.Button button1;
    private javax.swing.JTextField identifiant;
    private javax.swing.JLabel identifiantLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
