/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncolis.view;

import gestioncolis.Extras;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import gestioncolis.dao.*;
import gestioncolis.model.*;

/**
 *
 * @author Yassine
 */
public class Inscription extends javax.swing.JFrame {

    /**
     * Creates new form Inscription
     */
    public Extras extra = new Extras();
    public int Connected = 0;
    public Inscription() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(Physique);
        bg.add(Morale);
        Physique.setSelected(true);
        if(extra.NetworkConnectionVerify()){
            Connected = 1;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Physique = new javax.swing.JRadioButton();
        Morale = new javax.swing.JRadioButton();
        labelId = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label1Text = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AddressText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Label2Text = new javax.swing.JTextField();
        Ds = new javax.swing.JLabel();
        EmailZone = new javax.swing.JLabel();
        TelephoneText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Code_postalText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tempsText = new cambodia.raven.Time();
        Valider = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Inscription");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type Client", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 204))); // NOI18N

        Physique.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Physique.setText("Physique");
        Physique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhysiqueActionPerformed(evt);
            }
        });
        Physique.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhysiqueKeyPressed(evt);
            }
        });

        Morale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Morale.setText("Morale");
        Morale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoraleActionPerformed(evt);
            }
        });

        labelId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelId.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(Physique)
                .addGap(154, 154, 154)
                .addComponent(Morale, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Physique)
                    .addComponent(Morale))
                .addGap(37, 37, 37)
                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information Personnel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        Label1.setText("Designation :");

        Label2.setText("CIN:");

        Label1Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Label1TextActionPerformed(evt);
            }
        });

        jLabel7.setText("Adresse :");

        jLabel8.setText("Email :");

        TelephoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelephoneTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Numero de telephone:");

        Code_postalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Code_postalTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Code postal:");

        jLabel3.setText("Temps de reception");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Label1)
                        .addComponent(Label1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(AddressText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(TelephoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Ds, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempsText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(Label2)
                        .addComponent(Label2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(Code_postalText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailZone, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(114, 114, 114))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel10))
                            .addComponent(tempsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Code_postalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TelephoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Valider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        Annuler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(64, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(457, 457, 457)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(419, 419, 419)
                                .addComponent(Valider)
                                .addGap(34, 34, 34)
                                .addComponent(Annuler)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Annuler)
                    .addComponent(Valider))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhysiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhysiqueActionPerformed
            if(Physique.isSelected()){
                Label1.setText("Designation:");
                Label2.setText("CIN:");
            }else if(Morale.isSelected()){
                Label1.setText("Nom:");
                Label2.setText("ICE:");
            }
    }//GEN-LAST:event_PhysiqueActionPerformed

    private void PhysiqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhysiqueKeyPressed

    }//GEN-LAST:event_PhysiqueKeyPressed

    private void MoraleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoraleActionPerformed
        if(Physique.isSelected()){
                Label1.setText("Designation:");
                Label2.setText("CIN:");
            }else if(Morale.isSelected()){
                Label1.setText("Nom");
                Label2.setText("ICE:");
            }
    }//GEN-LAST:event_MoraleActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void Label1TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Label1TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label1TextActionPerformed

    private void TelephoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelephoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelephoneTextActionPerformed

    private void Code_postalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Code_postalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Code_postalTextActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        
        if(checkEmpty()){
            JOptionPane.showMessageDialog(null,"Entrer tous les donnees demander");
        }else{
            String email,address,telephone,code_postal,temps,password;
            email = EmailText.getText();
            address = AddressText.getText();
            telephone = TelephoneText.getText();
            code_postal = Code_postalText.getText();
            temps = tempsText.getSelectedTime();
            password = extra.generatePassword();
            if(Physique.isSelected()){
                String designation,cin;
                designation = Label1Text.getText();
                cin = Label2Text.getText();
                
                Person_Physique person = new Person_Physique(designation,telephone,email,address,code_postal,cin,temps,password);
                Person_PhysiqueDao person_physiquedao = new Person_PhysiqueDao();
                
                if(!checkCin(cin)){
                    JOptionPane.showMessageDialog(null, "CIN invalid");
                    Label2Text.setText("");
                }else{
                    
                
                
                if(!person_physiquedao.CheckPersonExistence(email)){
                    extra.sendEmail(email, "Get your password ", "Your password is "+password);
                if(person_physiquedao.insertPerson(person)){
                    if(Connected == 1){
                         JOptionPane.showMessageDialog(null,"Ajoute en success. Mot de passe est envoye en mail");
                         setEmpty();
                         this.setVisible(false);
                         new Login().setVisible(true);
                         
                    }else{
                        JOptionPane.showMessageDialog(null,"Ajoute en success. Mot de passe est "+password);
                        setEmpty();
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Erreur en ajout");
                }
                }else{
                    JOptionPane.showMessageDialog(null, "Email already exists");
                }
              }
                
            }else if(Morale.isSelected()){
                String nom,ice;
                nom = Label1Text.getText();
                ice = Label2Text.getText();
                
                if(!checkICE(ice)){
                    JOptionPane.showMessageDialog(null,"ICE invalid");
                    Label2Text.setText("");
                    
                }else{
                
                Person_Morale person = new Person_Morale(nom,telephone,email,address,code_postal,ice,temps,password);
                Person_MoraleDao person_moraledao = new Person_MoraleDao();
                if(!person_moraledao.CheckPersonExistence(email)){
                    extra.sendEmail(email, "Get your password ", "Your password is "+password);
                if(person_moraledao.insertPerson(person)){
                    if(Connected == 1){
                        JOptionPane.showMessageDialog(null,"Ajoute en success. Mot de passe est envoye en mail");
                        setEmpty();
                        Physique.setSelected(true);
                        this.setVisible(false);
                        new Login().setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null,"Ajoute en success. Mot de passe est "+password);
                        setEmpty();
                        Physique.setSelected(true);
                    }
                
                    
                }else{
                    JOptionPane.showMessageDialog(null,"Erreur en ajout");
                }
                
                }else{
                    JOptionPane.showMessageDialog(null,"Email already exists");
                }
                
                }    
                    
                    
                
                
            }
            
            
        }
        
    }//GEN-LAST:event_ValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscription().setVisible(true);
            }
        });
    }
    
    public void setEmpty(){
        Label1Text.setText("");
        Label2Text.setText("");
        EmailText.setText("");
        AddressText.setText("");
        Code_postalText.setText("");
        TelephoneText.setText("");
    }
    
    public boolean checkEmpty(){
        return ("".equals(Label1Text.getText()) || "".equals(Label2Text.getText()) || "".equals(EmailText.getText()) || "".equals(AddressText.getText())
                || "".equals(TelephoneText.getText()) || "".equals(Code_postalText.getText()));
    }

    
    public boolean checkCin(String cin){
        return cin.length() <= 8;
    }
    
    public boolean checkICE(String ice){
        return ice.length() <= 12;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressText;
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField Code_postalText;
    private javax.swing.JLabel Ds;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel EmailZone;
    private javax.swing.JLabel Label1;
    private javax.swing.JTextField Label1Text;
    private javax.swing.JLabel Label2;
    private javax.swing.JTextField Label2Text;
    private javax.swing.JRadioButton Morale;
    private javax.swing.JRadioButton Physique;
    private javax.swing.JTextField TelephoneText;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelId;
    private cambodia.raven.Time tempsText;
    // End of variables declaration//GEN-END:variables
}
