/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncolis.view;

import gestioncolis.dao.*;
import gestioncolis.model.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Yassine
 */
public class Parametre_Compte extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    Person_Physique person1 = null;
    Person_Morale person2 = null;
    
    Person_PhysiqueDao ppdao = new Person_PhysiqueDao();
    Person_MoraleDao pmdao= new Person_MoraleDao();
    public Parametre_Compte() {
        initComponents();
       
    }
    
    public Parametre_Compte(Person_Physique person) {
        initComponents();
        this.person1 = person;
        setUserInfo(ppdao.getPersonById(person.getId()));
    }
    
    public Parametre_Compte(Person_Morale person) {
        initComponents();
        this.person2 = person;
        setUserInfo(pmdao.getPersonById(person.getId()));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailZone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label1Text = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AddressText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Label2Text = new javax.swing.JTextField();
        TelephoneText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Code_postalText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tempsText = new cambodia.raven.Time();
        Modifier = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Parametre");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information Personnel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        Label1.setText("Designation :");

        Label2.setText("CIN:");

        Label1Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Label1TextActionPerformed(evt);
            }
        });

        jLabel7.setText("Adresse :");

        jLabel8.setText("Email :");

        TelephoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelephoneTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Numero de telephone:");

        Code_postalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Code_postalTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Code postal:");

        jLabel3.setText("Temps de reception");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Label1)
                        .addComponent(Label1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(AddressText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(TelephoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempsText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(104, 104, 104)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Label2)
                    .addComponent(Label2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Code_postalText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(Label2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel3)
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Code_postalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelephoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        Modifier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Modifier.setText("Modifier");
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });

        Annuler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Annuler))
                            .addComponent(Modifier))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Modifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Annuler)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Label1TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Label1TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label1TextActionPerformed

    private void TelephoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelephoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelephoneTextActionPerformed

    private void Code_postalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Code_postalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Code_postalTextActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
       if(checkEmpty()){
           JOptionPane.showMessageDialog(null,"Entrer des information correct");
           if(person1!= null)
               setUserInfo(person1);
           else if(person2!=null)
               setUserInfo(person2);
           else
               JOptionPane.showMessageDialog(null, "Error identifying person");
       }else{
           if(person1!=null){
               Person_Physique p = getUserInfoPhysique();
               if(ppdao.updatePerson(person1.getId(),p)){
                   JOptionPane.showMessageDialog(null,"Updated");
               }else{
                   JOptionPane.showMessageDialog(null,"Update failed");
               }
           }else if(person2 !=null){
               Person_Morale p = getUserInfoMorale();
               if(pmdao.updatePerson(person1.getId(),p)){
                   JOptionPane.showMessageDialog(null,"Updated");
               }else{
                   JOptionPane.showMessageDialog(null,"Update failed");
               }
               
           }else{
               JOptionPane.showMessageDialog(null, "Error identifying person");
           }
           
           
       }
        
        
    }//GEN-LAST:event_ModifierActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametre_Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametre_Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametre_Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametre_Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parametre_Compte().setVisible(true);
            }
        });
    }
        
    public boolean checkEmpty(){
        return ("".equals(Label1Text.getText()) || "".equals(Label2Text.getText()) || "".equals(EmailText.getText()) || 
                "".equals(Code_postalText.getText()) || "".equals(TelephoneText.getText()) || "".equals(AddressText.getText()) || 
                "".equals(tempsText.getText()));
    }
    
    public void setUserInfo(Person_Physique person){
        Label1Text.setText(person.getDesignation());
        Label2Text.setText(person.getCIN());
        EmailText.setText(person.getEmail());
        Code_postalText.setText(person.getCode_postal());
        TelephoneText.setText(person.getTelephone());
        AddressText.setText(person.getAddress());
        tempsText.setToolTipText(person.getTemps());
        Label1.setText("Designation:");
        Label2.setText("CIN:");
    }
    
    public void setUserInfo(Person_Morale person){
        Label1Text.setText(person.getNom());
        Label2Text.setText(person.getIce());
        EmailText.setText(person.getEmail());
        Code_postalText.setText(person.getCode_postal());
        TelephoneText.setText(person.getTelephone());
        AddressText.setText(person.getAddress());
        tempsText.setToolTipText(person.getTemps());
        Label1.setText("Nom:");
        Label2.setText("Ice:");
    }
    
    public Person_Physique getUserInfoPhysique(){
        String designation = Label1Text.getText();
        String cin = Label2Text.getText();
        String email = EmailText.getText();
        String code_postal = Code_postalText.getText();
        String telephone = TelephoneText.getText();
        String address = AddressText.getText();
        String temps  = tempsText.getText();
        
        return new Person_Physique(designation,telephone,email,address,code_postal,cin,temps);
    }
    
    public Person_Morale getUserInfoMorale(){
        String nom = Label1Text.getText();
        String ice = Label2Text.getText();
        String email = EmailText.getText();
        String code_postal = Code_postalText.getText();
        String telephone = TelephoneText.getText();
        String address = AddressText.getText();
        String temps  = tempsText.getText();
        
        return new Person_Morale(nom,telephone,email,address,code_postal,ice,temps);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressText;
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField Code_postalText;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel EmailZone;
    private javax.swing.JLabel Label1;
    private javax.swing.JTextField Label1Text;
    private javax.swing.JLabel Label2;
    private javax.swing.JTextField Label2Text;
    private javax.swing.JButton Modifier;
    private javax.swing.JTextField TelephoneText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private cambodia.raven.Time tempsText;
    // End of variables declaration//GEN-END:variables
}
